chore(release): tag version

diff --git a/.github/workflows/docker_release.yml b/.github/workflows/docker_release.yml
--- a/.github/workflows/docker_release.yml
+++ b/.github/workflows/docker_release.yml
@@ -20,21 +20,16 @@ jobs:
         id: set_tag_version
         run: | 
           if [[ "${{ github.event.client_payload.tagversion }}" != "" ]]; then
-           echo ::set-output name=tagversion::${{ github.event.client_payload.tagversion }}
-          elif [[ $GITHUB_REF != "" ]]; then
-           echo ::set-env name=tagversion::$(egrep -o '(v[0-9]+\.[0-9]+\.[0-9]+)(-.*)?' <<< $GITHUB_REF)
-            if [[$tagversion == ""]]; then
-             exit 1
-          else
-           echo "::error::Incorrect tag provided, please check and try again"
-           exit 1
+          echo ::set-output name=tagversion::${{ github.event.client_payload.tagversion }}
+          fi
+          if [[ $GITHUB_REF != "" ]]; then
+          echo ::set-env name=tagversion::$(egrep -o '(v[0-9]+\.[0-9]+\.[0-9]+)(-.*)?' <<< $GITHUB_REF)
+          fi
+          if [[ $tagversion == "" ]]; then
+          echo "::error::Incorrect tag provided, please provide a tag with the correct format and try again"
+          exit 1
           fi
           echo $tagversion
-      - name: Set env
-        run: | 
-             echo ${{ steps.set_tag_version.outputs.tagversion }}
-             echo ${{ steps.set_tag_version.outputs.tagversion }}
-             echo $tagversion
       - name: Docker login
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
       - name: Build production docker image
